In [2]:
# Defining the function

def function(x):

# Manually enter the function in the return statement

    return 5*x**4 - 4*x**2 + 2*x -3

In [3]:
import numpy as np

initial_set = np.linspace(-100,100,21)

In [4]:
temp=10000000

for i in range (len(initial_set)):

    if (function(initial_set[i]))<=(temp):

        temp = function(initial_set[i])

        first = function(initial_set[i])
        
        j = initial_set[i] 
    
    else:
    
        continue

print(temp)

print(j)

-3.0
0.0


In [10]:
initial_set

array([-100.,  -90.,  -80.,  -70.,  -60.,  -50.,  -40.,  -30.,  -20.,
        -10.,    0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,
         80.,   90.,  100.])

In [5]:
second_list= np.linspace(-10,10,41)

for i in range (len(second_list)):

    if (function(second_list[i]))<=(temp):

        temp = function(second_list[i])

        first = function(second_list[i])

        k = i

        j = second_list[i] 

    else:

        continue

print(temp)

print(j)

-4.6875
-0.5


In [11]:
second_list

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5,  10. ])

In [6]:
third_list = np.linspace(-1,0,41)

for i in range (len(third_list)):

    if (function(third_list[i]))<=(temp):

        temp = function(third_list[i])

        first = function(third_list[i])

        k = i

        j = third_list[i] 

    else:

        continue

print(temp)

print(j)

-5.171091796875
-0.725


In [12]:
third_list

array([-1.   , -0.975, -0.95 , -0.925, -0.9  , -0.875, -0.85 , -0.825,
       -0.8  , -0.775, -0.75 , -0.725, -0.7  , -0.675, -0.65 , -0.625,
       -0.6  , -0.575, -0.55 , -0.525, -0.5  , -0.475, -0.45 , -0.425,
       -0.4  , -0.375, -0.35 , -0.325, -0.3  , -0.275, -0.25 , -0.225,
       -0.2  , -0.175, -0.15 , -0.125, -0.1  , -0.075, -0.05 , -0.025,
        0.   ])

In [7]:
fourth_list = np.linspace(-0.75,-0.70,41)

for i in range (len(fourth_list)):

    if (function(fourth_list[i]))<=(temp):

        temp = function(fourth_list[i])

        first = function(fourth_list[i])

        k = i

        j = fourth_list[i] 

    else:

        continue

print(temp)

print(j)

-5.171761952929687
-0.7324999999999999
